#!/bin/bash

sudo su

cat << EOF > /lib/systemd/system/nginx-lua.service
[Unit]
Description=Nginx Container
After=docker.service
Requires=docker.service

[Service]
TimeoutStartSec=30s
StandardInput=tty-force
Restart=always
ExecStart=/usr/bin/docker run --name nginx-lua -it -p 8080:8080 username1366/nginx-lua:latest
ExecStop=/usr/bin/docker rm -f nginx-lua

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl start nginx-lua
systemctl enable nginx-lua


until docker ps
do
  systemctl restart nginx-lua
done
